### ISSUE TITLE
raw needs way to set the load address

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#100]
The raw file load dialog needs a way to set the load address (not just the target architecture).

**Comment by lambdafu** [comment]
I helped myself with a custom MOS-6502 loader in my branch: 015033f8
Turns out the raw image has a 2-byte header with the load address, so that
```
LOAD "file",8, 1
```
(secondary addressing 1) works on the C64.

**Comment by flanfly** [comment]
Fixed with #131
