### ISSUE TITLE
interrupt vector may be indirect

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#109]
Currently, interrupt_vec, int_vec and project raw loader assume that interrupt vectors are entry points.  So far, the code is only used on specific platform targets, so it may be considered target specific.  However, as it is spread out a bit, there is probably an assumption about a (future?) more general approach.

On 6502, intterupt/rest/etc vectors are indirectly addressed jumps - the entry point is read from the given memory address.  Should this be supported generally or kept platform specific?

**Comment by lambdafu** [comment]
See 3096db52ee5c4716c36a982f5b6369b2ce09de43

**Comment by flanfly** [comment]
Changing CallTarget::Todo to use Rvalue instead of u64 should suffice.
