### ISSUE TITLE
Invalid u16 literal 0x10000 breaks compilation

### ISSUE THREAD

**Issue by badboy** [das-labor/panopticon#137]
In [`parse.rs`](https://github.com/das-labor/panopticon/blob/master/lib/src/elf/parse.rs#L329):
0x10000 is not a valid u16, but is used in the match as `0xff00...0x10000 => ...`

Should be changed to `0xffff`. The `...` is inclusive, I guess `0xffff` should be part of `ProcessorSpecific` anyway? (this means the `0xfe00...0xff00` overlaps with the next one, so is `0xff00` a `OsSpecific` or `ProcessorSpecific`?)

Btw., instead doing the `v.to_u16.unwrap()`  thingy again in the match arm, just do `a @ 0xfe00...0xff00` and use `a` in the code.

**Comment by flanfly** [comment]
Good catch. ProcessorSpecific is 0xff00..0xffff (both inclusive).
