### ISSUE TITLE
README.md: dependencies in Ubuntu 16.04

### ISSUE THREAD

**Issue by garyhouston** [das-labor/panopticon#143]
The suggested apt-get command for Ubuntu 14.04 (AMD64) gives in Ubuntu 16.04:

Package libqt5qml-quickcontrols is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  qml-module-qtquick-controls:i386 qml-module-qtquick-controls

E: Package 'libqt5qml-quickcontrols' has no installation candidate

**Comment by jeandudey** [comment]
See #142.

**Comment by garyhouston** [comment]
Thanks.

**Comment by flanfly** [comment]
Merged, thanks alot.
