### ISSUE TITLE
No install instructions or link on the website

### ISSUE THREAD

**Issue by pirate** [das-labor/panopticon#144]
Absolutely no indication as to how to actually **get** this piece of software.  

Finally after 5 minutes I found the github link, which has very little marking indicating that it's actually a clickable link.

Would be nice to add a big, simple link labelled *install instructions* so that it doesn't take minutes of digging.

**Comment by jeandudey** [comment]
:+1:

**Comment by flanfly** [comment]
[Fixed](https://panopticon.re/get)
