### ISSUE TITLE
Make Rust 1.8 dependency clear on instructions

### ISSUE THREAD

**Issue by Coderdreams** [das-labor/panopticon#146]
When I attempted to test the program, I spent quite some time trying to get the rust dependencies installed on Ubuntu 14.04. The only apt repository I found: https://launchpad.net/~hansjorg/+archive/ubuntu/rust,  was one that is outdated now (latest version I think is 1.6 and fails on cargo build with a syntax error reading the Cargo.toml file).

**Comment by Coderdreams** [comment]
Also, after build, I get:

$ target/debug/qtpanopticon 
QQmlApplicationEngine failed to load component 
file:///home/xxx/panopticon/qml/Window.qml:20 module "QtQuick.Dialogs" version 1.2 is not installed

**Comment by jeandudey** [comment]
Use [multirust](https://github.com/brson/multirust) or [rustup.sh](https://github.com/rust-lang/rustup.sh) since .deb packages of Rust get outated quickly.

Also for the second issue install `libqt5qml-quickcontrols`.

**Comment by lerela** [comment]
For the second issue the package `libqt5qml-quickcontrols` is already part of the installation instructions, the problem is there even if it is installed.

**Comment by Coderdreams** [comment]
For the first issue, I recommended updating the README file so that others using Ubuntu don't get confused.

**Comment by flanfly** [comment]
I extended the README to include the Rust version and the necessary packages on Ubuntu.
