### ISSUE TITLE
Ubuntu 16.04LTS build failure

### ISSUE THREAD

**Issue by silverdr** [das-labor/panopticon#153]
After installing rust/cargo and the dependencies from readme file, I get the following result when trying to build from a freshly cloned repository:

```
silverdr@ubuntu1604:~/sources/panopticon$ cargo build
failed to parse manifest at `/home/silverdr/sources/panopticon/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:34:9 expected a key but found an empty string
Cargo.toml:34:9-34:10 expected `.`, but found `'`
```
Are there still some undocumented dependencies that I need to install?

**Comment by flanfly** [comment]
What's the output of `rustc --version`?

**Comment by silverdr** [comment]
```
silverdr@ubuntu1604:~$ rustc --version
rustc 1.7.0
```
the default that install on Ubuntu 16.04LTS.

**Comment by flanfly** [comment]
You need the current stable version of Rust (1.8.0) in order to compile Panopticon. You can get that on https://rust-lang.org/

**Comment by silverdr** [comment]
1.8.0 seems to be of 2016-04-16, IOW less than a month old and Panopticon already *depends* on it? If that's the case, it would be nice to have a line on this in the readme.md. Especially that Ubuntu 16.04 is quite fresh and (myself not excluded) people often dislike patching fresh distros with "unofficial" sources.

**Comment by flanfly** [comment]
Ok, the dependency on 1.8.0 isn't hard to relax. I think it's worth it if we get Ubuntu 16.04 support.

**Comment by silverdr** [comment]
That would surely be great, thanks.

**Comment by flanfly** [comment]
Reopen if it still does not build.

**Comment by silverdr** [comment]
Just to confirm - after pulling the updated Cargo.toml it emits some warnings about:

* raw_pointer_derive (libc v0.1.12)
* pub extern crate (num v0.1.32)

plus lots of warnings, mostly about unused imports and unused variables in panopticon itself. Some looking more dangerously:

```
warning: unused result which must be used,
```
but theoretically builds into `target/debug/qtpanopticon`.

When trying to run - it says:
```
silverdr@ubuntu1604:~/sources/panopticon$ target/debug/qtpanopticon 
OpenGL Warning: glXCreatePbuffer not implemented by Chromium
appmenu-qt: handleReparent 138 The given QWindow has no QMenuBar assigned
```
and I don't seem to get anything beyond a big window with logo in the middle.
