### ISSUE TITLE
OS X Build Success, but just a Splash Screen

### ISSUE THREAD

**Issue by ibuick** [das-labor/panopticon#154]
<img width="1112" alt="screen shot 2016-05-12 at 10 34 27 pm" src="https://cloud.githubusercontent.com/assets/880847/15218291/d90f3f96-1891-11e6-920e-b86e969124ca.png">

Build with following steps:

1. git clone
2. cargo build --verbose
3. cargo test --verbose
4. cargo run

All test are passed:

![Uploading Screen Shot 2016-05-12 at 10.37.05 PM.png…]()

**Comment by 86me** [comment]
What are you expecting to see? Check the menu, try opening something (command + O)
