### ISSUE TITLE
Distribute Binary Packages

### ISSUE THREAD

**Issue by rzabcik** [das-labor/panopticon#155]
It takes upwards of 10 minutes to finish building and start testing, but then it runs out of memory and aborts.

**Comment by flanfly** [comment]
I was able to build Panopticon in a VM w/ 2GB RAM. It's definitely resource intensive, though. Sadly there isn't much I can do about it the compile process :-/

**Comment by rzabcik** [comment]
Could you post a binary?

**Comment by flanfly** [comment]
Now that Rust is in Ubuntu I can make a DEB package for Panopticon.

**Comment by flanfly** [comment]
There are now prebuilt .deb for Ubuntu and Debian.
