### ISSUE TITLE
Rendering issues on Fedora

### ISSUE THREAD

**Issue by cyplo** [das-labor/panopticon#183]
Hello ! 
I've built Panopticon from master at 8aaccc6678a45d2c6ef85d02becef615b99c9b4b and it runs.
However, it seems to have some rendering problems.
My system is Fedora 24, running Intel's card and drivers:
GL_RENDERER   = Mesa DRI Intel(R) HD Graphics 5300 (Broadwell GT2) 
GL_VERSION    = 3.0 Mesa 12.0.1
GL_VENDOR     = Intel Open Source Technology Center

Let me know if I can somehow help.

Thanks a lot !

![screenshot from 2016-08-07 11-37-59](https://cloud.githubusercontent.com/assets/217899/17461633/d8232d0e-5c93-11e6-965c-ef6f099c6aa4.png)
![screenshot from 2016-08-07 11-38-06](https://cloud.githubusercontent.com/assets/217899/17461634/d824cf92-5c93-11e6-8980-0c059eae00e8.png)
![screenshot from 2016-08-07 11-38-13](https://cloud.githubusercontent.com/assets/217899/17461635/d8271c16-5c93-11e6-9524-02212d5f42b0.png)

**Comment by flanfly** [comment]
Hey @cyplo, there were some files missing in master. Also it seems the Gnome Shell has some problems /w QML. Please try again with the current master.

**Comment by cyplo** [comment]
Hey ! Seems much better, cannot find any visual artifacts after a minute of clicking.

thanks !

**Comment by flanfly** [comment]
Great! Just reopen the issue if you still have problems.
