### ISSUE TITLE
Won't start on macOS 10.11.6

### ISSUE THREAD

**Issue by sphinxc0re** [das-labor/panopticon#192]
When starting panopticon on my macbook, it throws an error:
<img width="961" alt="bildschirmfoto 2016-08-12 um 11 23 06" src="https://cloud.githubusercontent.com/assets/3702016/17618322/4e0cbc26-607f-11e6-9e6e-1dc8125fbd84.png">

**Comment by flanfly** [comment]
Thanks for the bug report! It should work with the current master now.
