### ISSUE TITLE
Undocumented dependency

### ISSUE THREAD

**Issue by est31** [das-labor/panopticon#201]
Hi, I'm an Ubuntu 16.10 user and couldn't get panopticon started unless I installed the `qtdeclarative5-models-plugin` package. Would be cool to add it to the readme. Thank you!

**Comment by bkircher** [comment]
I get following when I try to start panopticon:
```
~/panopticon/target/release$ ./qtpanopticon 
QQmlApplicationEngine failed to load component
file:///home/ubuntu/panopticon/qml/Title.qml:22 module "QtQuick.Dialogs" is not installed
```

This is on a pristine 16.04 LTS. I build panopticon exactly as described in the README with:
```
curl -s -O https://static.rust-lang.org/rustup.sh
sh rustup.sh
sudo apt install -y \
	build-essential \
	cmake \
	git \
	pkg-config \
	qml-module-qtgraphicaleffects \
	qml-module-qtquick-controls \
	qml-module-qtquick-layouts \
	qml-module-qtquick2 \
	qml-module-qttest \
	qt5-default \
	qtbase5-private-dev \
	qtdeclarative5-dev \

git clone https://github.com/das-labor/panopticon.git
pushd panopticon
cargo build --release
popd
```

Installing `qtdeclarative5-models-plugin` doesn't change anything here, so this might be totally unrelated to OP.

The Internet says that 

> You need to deploy the required modules with the application. They are located inside qml subdirectory of your Qt installation. 

[Source at qtcentre.org](http://www.qtcentre.org/threads/60907-How-to-distribute-a-qt-quick-application-to-a-computer-without-QT-installed)

**Comment by flanfly** [comment]
Thanks for the bug report! I added ``qtdeclarative5-models-plugin`` to the README. The problem of @bkircher is due some other missing dependency.
