### ISSUE TITLE
File picker needs a 2nd click to receive focus

### ISSUE THREAD

**Issue by flanfly** [das-labor/panopticon#215]

**Comment by flanfly** [comment]
Meh, will just throw the picker away and use the native one.

**Comment by m4b** [comment]
:( I liked the little ELF, PE, Mach file hints... can we still do something like that with native ?

**Comment by flanfly** [comment]
No. For now, Qt does not allow you to customize the open dialog using only QML. In case that feature is added we can think about it. The file picker was a lot (buggy) code that wasn't really worth it.

I'm not opposed keeping the picker if some else takes care of it.

**Comment by m4b** [comment]
It's not too important. And yes was buggy. It's also less code to maintain so I'm ok with it going away, but just a little sad to see those file hints disappearing :)
