### ISSUE TITLE
need to be able to zoom out call graphs

### ISSUE THREAD

**Issue by m4b** [das-labor/panopticon#230]
For large graphs navigation becomes difficult without a zoom out/in

**Comment by flanfly** [comment]
Mouse wheel should zoom. At least it should, I remember programming this :laughing:.

**Comment by m4b** [comment]
My mouse wheel seems to scroll up and down

**Comment by flanfly** [comment]
What about Ctrl+Mouse Wheel?

**Comment by m4b** [comment]
:sob:

**Comment by flanfly** [comment]
Note to self: This should be documented :rofl:
