### ISSUE TITLE
UX issue: symbol names overlap address

### ISSUE THREAD

**Issue by m4b** [das-labor/panopticon#231]
symbol names overlap address value
![screenshot from 2017-01-24 22-15-55](https://cloud.githubusercontent.com/assets/1920204/22279575/57bcb95a-e280-11e6-9be7-54a13dba500d.png)

Probably need to move to be able to drag the name/offset table size over to the right, or better yet, have it auto-calculate the width given the largest symbol name?

**Comment by flanfly** [comment]
Yeah, at least it should elide the end of the symbol names. I'm working on moving the UI code from `qmlrs` to `qml-rust` which is a bit better designed. The new code will allow to adjust the side bar width, hopefully this fixes the problem.

**Comment by m4b** [comment]
Cool awesome! Looking forward to it. Also we elision good idea too, might be easiest, then perhaps clicking a symbol displays the name at the top in the cfg area?

**Comment by flanfly** [comment]
I was thinking about something like a tooltip that shows the full name of the function when you hover over the elided name.

**Comment by m4b** [comment]
Tooltip works, could also put to the right of the "control flow" tab on the right screen.

Although both could have similar issues when presented with some of the extremely large c++ names. Although then again in those cases full name not so important?

While I'm here, and sorry if this is somewhat unrelated, but I was thinking of maybe a meta tracker issue for "UI Wishlist", and first thing I noticed is that QT receives the address of an operand (which is awesome) so it would be really cool if clicking a valid address displayed the cfg of that (and then maybe have a back button). Dunno just some thoughts

**Comment by m4b** [comment]
This is fixed in #283, great job!
