### ISSUE TITLE
Radare2-regressions repository

### ISSUE THREAD

**Issue by Maijin** [das-labor/panopticon#240]
Hello,

I noticed many binaries ELF/PE doesn't load at all on panopticon without any explanation which it makes it completely unreliable aka useless.

Please check the https://github.com/radare/radare2-regressions (bins folder). It contains binaries that have been made/found for fuzzing/enhancing PE/ELF/... engine of radare2 same for the disassembly tests.

**Comment by flanfly** [comment]
Coolbeans man I'll check it out. I didn't know r2 had a test suite. Keeping it completely separate from the actual code base makes it especially useful :+1:

**Comment by Maijin** [comment]
Cool 👍
