### ISSUE TITLE
Qt UI color theme conflict with a dark KDE theme

### ISSUE THREAD

**Issue by vflyson** [das-labor/panopticon#246]
Apparently KDE alters the default Qt color settings, which results in other applications inheriting those color values.
![panopticon-open-dialog](https://cloud.githubusercontent.com/assets/1392048/22866178/c0e2cd98-f13f-11e6-8f08-4d9b1c83290e.png)
![panoption-main-window](https://cloud.githubusercontent.com/assets/1392048/22866179/c0e4afa0-f13f-11e6-98e4-1422d3e894b6.png)

**Comment by ehntoo** [comment]
Did some experimentation since I ran into this on my Arch box - a patch to the upstream qmlrs fork takes care of it:
```diff --git a/ext/libqmlrswrapper/libqmlrswrapper.cpp b/ext/libqmlrswrapper/libqmlrswrapper.cpp
index b0e4520..ebae769 100644
--- a/ext/libqmlrswrapper/libqmlrswrapper.cpp
+++ b/ext/libqmlrswrapper/libqmlrswrapper.cpp
@@ -34,6 +34,7 @@ rust_fun QrsApplicationEngine *qmlrs_create_engine(const char *name, unsigned in
 
         int *argc = (int *)malloc(sizeof(int));
         *argc = 1;
+        QGuiApplication::setDesktopSettingsAware(false);
 
         new QGuiApplication(*argc, argp);
     }
```

I'm unsure what other effects this has on the app, though.
