### ISSUE TITLE
create panopticon-cli

### ISSUE THREAD

**Issue by flanfly** [das-labor/panopticon#260]
Add a command line interface to the is helpful for prototyping features and using Panopticon in batch processing. The tool shall be named `panop` and accepts files to disassemble as arguments. Each file is disassembled and functions are printed w/ their metadata on the console.

`panop [OPTIONS...] [FILES...]`

# Options
`--avr <mcu>`: Assume `[FILES...]` are AVR flash dumps for MCU `<mcu>`.
`--mos6502`: Assume `[FILES...]` are MOS-6502 flash dumps.
`--elf`: Assume `[FILES...]` are ELF (default).
`--help,-h`
`--version,-V`

**Comment by m4b** [comment]
I believe we have a prototype implementing this in #305; should we close?

**Comment by flanfly** [comment]
Agree
