### ISSUE TITLE
Generating documentation fails

### ISSUE THREAD

**Issue by flanfly** [das-labor/panopticon#265]
Since https://github.com/das-labor/panopticon/commit/c460ecd6037ec95393a26255bc673ef28fb46155 calling `cargo doc` crashes. I disabled the test on Travis and reported the issue upstream https://github.com/rust-lang/rust/issues/40936.

**Comment by Aaron1011** [comment]
This is now fixed in the latest nightly rust.

**Comment by m4b** [comment]
@Aaron1011 awesome thank you for fixing the upstream issue ! :)
