### ISSUE TITLE
Add development guidelines to README

### ISSUE THREAD

**Issue by flanfly** [das-labor/panopticon#270]
# For contributors
 1. Please have fun, nobody is paid for developing Panopticon.
 1. Everything is up to debate, none of the following guidelines is set in stone.
 1. I you want to help, check out the easy issues.
 1. If you want a feature, open an issue _before_ you're dumping your 5k line patch, small bug fixes are ok.
 1. Format w/ rust-fmt before submitting.
 1. Please add tests, at least one positive and one negative test. Make sure the coverage doesn't decrease.
 1. Consider splitting your change into multiple smaller ones.
 1. All CI jobs must pass. You have an infinite amount of tries.

# For maintainers & reviewers
 1. Assume good faith.
 1. Please have fun, nobody is paid for developing Panopticon.
 1. Everything is up to debate, none of the following guidelines is set in stone.
 1. Check whenever contributed code:
     1. scales reasonable well,
     1. has no (obvious) security problems,
     1. isn't reimplementing features that exist in Panopticon already,
     1. is in the right place,
     1. comes w/ unit tests that demonstrate the code works and make sure it can be changed later,
     1. includes legible documentation.
1. No bikeshedding about naming, brace placement, argument order, "taste" or "style".
1. If in doubt, merge. (**EDIT**)
1. Please thank the contributor. It costs nothing. Also, see 2.

/cc @m4b @sphinxc0re 
Part of #267

**Comment by sphinxc0re** [comment]
Usually, contribution guidelines belong into the `CONTRIBUTING.md` file, not in the `README.md`

**Comment by flanfly** [comment]
Yeah, it got a bit long :joy:

**Comment by sphinxc0re** [comment]
Other than that, this looks really good.

**Comment by m4b** [comment]
LGTM.

Also this made me lol:

>  You have an infinite amount of tries.
