### ISSUE TITLE
thread '<unnamed>' panicked at 'not yet implemented'

### ISSUE THREAD

**Issue by tiensonqin** [das-labor/panopticon#280]
Great work!

Error log below:

thread '<unnamed>' panicked at 'not yet implemented', lib/src/amd64/mod.rs:2362
ERROR:qtpanopticon::project: error while disassembling Uuid("abfc1a0c-5780-454d-a67f-15c05b0e6cdb"): Any
thread '<unnamed>' panicked at 'not yet implemented', lib/src/amd64/mod.rs:2362
ERROR:qtpanopticon::project: error while disassembling Uuid("abfc1a0c-5780-454d-a67f-15c05b0e6cdb"): Any
thread '<unnamed>' panicked at 'not yet implemented', lib/src/amd64/mod.rs:2362
ERROR:qtpanopticon::project: error while disassembling Uuid("abfc1a0c-5780-454d-a67f-15c05b0e6cdb"): Any
thread '<unnamed>' panicked at 'not yet implemented', lib/src/amd64/mod.rs:2362
ERROR:qtpanopticon::project: error while disassembling Uuid("abfc1a0c-5780-454d-a67f-15c05b0e6cdb"): Any

**Comment by m4b** [comment]
Yarrrrgggg @flanfly this is the error/infinite loop i was just talking about ! the file `libbeef.dylib` in #277 should repro this

**Comment by flanfly** [comment]
The root cause seems to be the missing implementation of memory reads larger than 64 bits. I wonder why this causes an infinite loop :confused:. I'll look into it after I'm done with #274

**Comment by flanfly** [comment]
I implemented memory reads up to 256 bits. Should work now. Thanks, everybody!
