### ISSUE TITLE
Doesn't start on Windows 10

### ISSUE THREAD

**Issue by kirillkh** [das-labor/panopticon#306]
Console log:

```
Qt: Untested Windows version 10.0 detected!
QQmlApplicationEngine failed to load component
file:///H:/devel/Panopticon/qml/Panopticon/Window.qml:145 Type Sidebar unavailable
file:///H:/devel/Panopticon/qml/Panopticon/Sidebar.qml:4 module "QtQuick.Controls.Styles" version 1.4 is not installed
```

**Comment by flanfly** [comment]
Did you compile Panopticon yourself or did you use the precompiled version?

**Comment by kirillkh** [comment]
I used the precompiled version.

**Comment by rblenkinsopp** [comment]
I can confirm this behavior as well, using the latest download. I get exactly the same error message.

**Comment by flanfly** [comment]
The current [nightly](https://files.panopticon.re/panopticon-master.zip) should work. Sorry for the delay. Please reopen if the problem persists.
