### ISSUE TITLE
AVR: Boundary error in overflowing PC rjmp calculation

### ISSUE THREAD

**Issue by mbuesch** [das-labor/panopticon#31]
panopticon throws the following error
```
disassemble at 0
boundary err: 18446744073709549424 not inside 6002 byte large slab
1 procedures
proc_0(62786320): 2 bblocks
width: 6002
```

for the following AVR assembly program:
```
.include "m88def.inc"
.org 0
rjmp label
.org 3000
label: mov r1, r2
```

assembled with:
```
$ avra -I /usr/share/avra/ overflowtest.asm
$ avr-objcopy -m avr4 -I ihex -O binary overflowtest.hex overflowtest.bin
```

avr-objdump shows this:
```
$ avr-objdump -m avr4 --target=binary --disassemble-all overflowtest.bin 

overflowtest.bin:     file format binary


Disassembly of section .data:

00000000 <.data>:
       0:       b7 cb           rjmp    .-2194          ;  0xfffff770
        ...
    176e:       00 00           nop
    1770:       12 2c           mov     r1, r2
```

As can be seen, the rjmp uses an overflowing calculation to reach the target.
(18446744073709549424 is 0xFFFFFFFFFFFFF770)

Possible solution: Mask the calculated offset with (FLASHEND+1)*2-1

**Comment by flanfly** [comment]
Thanks for the bug report! Sadly, FLASHEND depends on the µC so the AVR disassembler in Panopticon has to be extended. Blocked by #38.

**Comment by mbuesch** [comment]
It still throws suspicious errors/warnings for me:

```
Qt: create AVR: ".../test.bin" (.../git/panopticon/qt/src/panopticon.cc:69, Session* Panopticon::createAvrSession(const QString&))
disassemble at 0
6000 2999 -1097 18446744073709549424
boundary err: 6002 not inside 6002 byte large slab
1 procedures
proc_0(66889536): 3 bblocks
width: 6002
Qt: qrc:/workspace/Graph.qml:94:14: Unable to assign [undefined] to QString (qrc:/workspace/Graph.qml:94, 
```

Note the large number 18446744073709549424 (= 0xFFFFFFFFFFFFF770), and the weird boundary error message.

**Comment by flanfly** [comment]
The 3rd line is just stale debugging output. The boundary err is probably because the disassembler fails to wrap the IP around after FLASHEND is reached.
