### ISSUE TITLE
crates.io releases?

### ISSUE THREAD

**Issue by philipc** [das-labor/panopticon#340]
I'm using the core and amd64 crates in [another project](https://github.com/gimli-rs/ddbug), which I would like to put on crates.io. Do you have plans to do crates.io releases for these crates?

**Comment by flanfly** [comment]
Hello @philipc, cool project! We want to release crates (I uploaded a dummy crate already: https://crates.io/crates/panopticon). The problem is that we're not settled on a stable API yet, and I'm unsure if it make sense to publish crate(s) before that.

**Comment by philipc** [comment]
You don't really need a stable API for pre 1.0 releases, but having releases does tend to make you more conservative about changes, so no rush. Thanks!
