### ISSUE TITLE
Assertion failed: program.hh:149

### ISSUE THREAD

**Issue by mbuesch** [das-labor/panopticon#51]
```
$ ./qt/qtpanopticon -a image.bin
```
[snip]
```
terminate called after throwing an instance of 'po::failed_assertion'
  what():  .../git/panopticon/lib/include/panopticon/program.hh: 149 assertion '(*wp.entry)->area().lower() == tgt' failed.
Aborted
```

**Comment by flanfly** [comment]
Happens after a call right into a function instead of calling to the first byte of the entry point. For now I think it's best to allocate a new procedure instance and ignore basic block sharing between them.

**Comment by flanfly** [comment]
I can't reproduce that error. Is there any change that you can upload the `image.bin` somewhere?
