### ISSUE TITLE
AVR: incorrect translation of sbi

### ISSUE THREAD

**Issue by mbuesch** [das-labor/panopticon#61]
The following program
```
.device atmega88
.org 0
sbi 5, 0
```
is disassembled to
```
sbi 5, 18446744071562067968
```
that is hex 0xFFFFFFFF80000000. Smells like some incorrect integer handling and/or some off by one error.
This is a 64 bit host system. Not tested on 32 bit.

**Comment by flanfly** [comment]
I agree, likely an overflow related problem.
