### ISSUE TITLE
AVR: Unusual translation of MOVW

### ISSUE THREAD

**Issue by mbuesch** [das-labor/panopticon#63]
This
```
.device atmega88
.org 0
movw r30, r24
```
results in this
```
movw r30, r31, r24, r25
```
avra does not understand this format, so it probably is not allowed.

**Comment by flanfly** [comment]
That's more or less a known problem. Mnemonics with more than two operands are still printed as ``mne op1, op2, op3, ...``. What I meant was ``movw r30:r31, r24:r25`` to convey that the opcode works on more than just r30 and r24. Looking back this was probably a bad idea as it confuses people.

**Comment by mbuesch** [comment]
I think we should not try to invent new mnemonics here and simply stay with what the original AVR assembler understands.
