### ISSUE TITLE
"Illegal hardware instruction"

### ISSUE THREAD

**Issue by osa1** [das-labor/panopticon#66]
I'm still trying to run this(since #64), this time I'm having this problem:

```
➜  panopticon git:(master) ./target/release/qtpanopticon 
[1]    18431 illegal hardware instruction  ./target/release/qtpanopticon
```

Compiled with `rustc 1.3.0` and bundled cargo.

Any ideas?

**Comment by osa1** [comment]
Stack trace again shows some deep qt function on startup. Closing this. I probably have a broken Qt setup.

**Comment by flanfly** [comment]
I though the same when I saw the issue. Qt is the only thing that hasn't changed since #64. Sorry you have such a bad experience with Panopticon. Have you installed Qt from the repositories or did you built it from source?
