### ISSUE TITLE
Save doesn't save

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#89]
Save shows a file open(?) dialog, not a file save dialog.  There is no input field to enter the filename, and clicking on an existing dummy panop file and pressing OK opens a subdiretory.

**Comment by flanfly** [comment]
At least on my machine there is a text entry on top where you can set the whole path of the file to be save, but you're right that it is not usable.

**Comment by lambdafu** [comment]
Ah, the trick is pressing ENTER instead of clicking OK.  Oh well.  At least *I* can save now. :dancer:
