### ISSUE TITLE
Add hex to instructions

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#91]
Instructions should be able to have their address and their hex in front of them (configurable?):

```
c002  85 01             STA     Z01                         ; Reset datasette, rom mirror
c004  20 5c c1         JSR     Sc15c                     ; Clear 0x2000 - 0x3fff (Bitmap)
```

This can be very important in difficult analysis situations, for example self-modifying code.  Also to spot analyser errors.

**Comment by flanfly** [comment]
The hexdump view had this. Still need to be ported #75

**Comment by lambdafu** [comment]
Yeah.
