### ISSUE TITLE
Revive hexdump view

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#93]
Data that is not analysed (because it is never reached, or because it is manually marked as raw data, see #92 ) should nevertheless be displayed in the call graph, to allow for eyeball analysis and interaction (manually marking it as instructions by setting new entrypoints, or marking ranges and setting the data format for example).

I guess as a first step it would be useful to append raw data to the head (for the first) or tail of an instruction chunk.  Many more options immediately come to mind.

**Comment by flanfly** [comment]
I really prefer to keep code and data separate. This is the most basic abstraction that can be extracted from machine code w/o much processing.

The C++ version had a linear "hexdump" view that interleaved code and data. It's still needs to be ported to the new API: #75

**Comment by lambdafu** [comment]
Hexview would be fine.  I changed the issue title.
