### ISSUE TITLE
Better diagnostics on thread panic

### ISSUE THREAD

**Issue by lambdafu** [das-labor/panopticon#96]
When the analyser dies, the program ends silently ("Working").  There needs to be better diagnostics for both, end users and developers (so maybe these are two tickets).

Example to provoke such a crash with a coding error: Add a bit pattern to a disassembler that is larger than the token length.  The program will output on the console:

```
thread '<unnamed>' panicked at 'shift operation overflowed', ../src/libcore/ops.rs:833
```

**Comment by lambdafu** [comment]
One trick is to run with RUST_BACKTRACE=1 in the environment.  This is a basic rust-n00b-thing.  However, the user part ist still relevant.

**Comment by flanfly** [comment]
#104
